### ISSUE TITLE
Input Field

### ISSUE THREAD

**Issue by sidharthpatel** [sidharthpatel/Contactify#1]
* Generate input boxes that are able to gather data regarding an individual's personal information
  * Ex. Name, emails, etc.

**Comment by Godwindaniel10** [comment]
Hi am Godwin, I will be so glad to work on this issue. 

Can I dive in ?

**Comment by sidharthpatel** [comment]
@Godwindaniel10 Sorry, but this is an in-class assignment. Feel free to contribute to any of my other repos tho.

**Comment by Godwindaniel10** [comment]
Ok cool 😊
